### PR TITLE
Add and use TrafficCommand input and TrafficCommandUpdate output

### LINKED ISSUE #3: TrafficCommand and TrafficCommandUpdate
grafik

I would like to extend the template by including the two optional interfaces TrafficCommand & TrafficCommandUpdate as mentioned in the [specification](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/sensor-model/spec/model_types.html)

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
**Reference to a related issue in the repository**
#3 

**Add a description**
- [x] Add TrafficCommand input and TrafficCommandUpdate output
- [x] Implement example reaction to incoming traffic action
- [x] Implement example dismissal as TrafficCommandUpdate

**Take this checklist as orientation for yourself, if this PR is ready for Maintainer Review**
- [x] My suggestion follows the [governance rules](https://openmsl.github.io/doc/OpenMSL/organization/governance_rules.html).
- [x] All commits of this PR are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] My changes generate no errors when passing CI tests. 
- [x] I updated all documentation (readmes incl. figures) according to my changes.
- [x] I have successfully implemented and tested my fix/feature locally.
- [x] Appropriate reviewer(s) are assigned.

### CODE REVIEW

**Comment by jdsika** [comment]
This is an improvement for you @nocll - feel free to exchange with @ClemensLinnhoff and review

**Comment by nocll** [comment]
@jdsika This PR would facilitate modeling non-ego traffic agents with the template.
So the agent can get action commands from a scenario engine, and can reply if the action was completed. This is of course an improvement for the template. Also good to be consistent with OSI spec.

However, this is not a feature I would use for now:

* For our use case we will focus first on packing the ego vehicle in this FMU template. So action commands do not apply
* Using this also requires re-working the environment simulator to send the TrafficCommand messages

On a related question -- maybe more an OSI issue: In [this definition](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/sensor-model/spec/model_types.html) do you know why **SensorData input** is not considered for the Traffic participant models?

* One could model a sensor with SensorData output, sending this information to a controller which decides how/where to move the agent
* This interface for a Traffic Participant (input: SensorData, output: TrafficUpdate) would be interesting for ego vehicle modeling

**Comment by ClemensLinnhoff** [comment]
> On a related question -- maybe more an OSI issue: In [this definition](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/sensor-model/spec/model_types.html) do you know why **SensorData input** is not considered for the Traffic participant models?

I fully agree. There should be a model type, that receives a SensorData and outputs a TrafficUpdate. I already created an issue in OSMP a while back to discuss this: https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/issues/102
It would be great, if you could comment there, to stress, that this is something, that is actually needed.

**Comment by ClemensLinnhoff** [comment]
> * Using this also requires re-working the environment simulator to send the TrafficCommand messages

We are already working on enabling esmini to provide the TrafficCommand message: https://github.com/esmini/esmini/issues/499

**Comment by nocll** [comment]
> It would be great, if you could comment there, to stress, that this is something, that is actually needed.

Ah good! OK I added a comment there.

**Comment by ClemensLinnhoff** [comment]
@jdsika reminder to review

**Review by jdsika — APPROVED** [review]

**Pull request merged**
